### ISSUE TITLE
Home Assistant TTS service stops working

### ISSUE THREAD

**Issue by pniewiadowski** [brenner-tobias/addon-cloudflared#123]
### The problem

Home Assistant TTS service stops working for me once I start using Cloudflared Add-On.

When I call a TTS service HA shows below error:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/network.py:201
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:02:14 PM (1 occurrences)
Last logged: 9:02:14 PM

[139727335055008] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 636, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 218, in async_say_handle
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 628, in async_play_media
    sourced_media = await media_source.async_resolve_media(
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 146, in async_resolve_media
    return await item.async_resolve()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 90, in async_resolve
    return await self.async_media_source().async_resolve_media(self)
  File "/usr/src/homeassistant/homeassistant/components/tts/media_source.py", line 68, in async_resolve_media
    if manager.base_url and manager.base_url != get_url(self.hass):
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 201, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```
My configuration.yaml:
```
http:
  base_url: https://url.com
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
...
tts:
  - platform: google_translate
    service_name: google_say
    base_url: https://url.com
```

Do you know if this can be fixed by configuration or I cannot use Cloudflared Add-On and TTS at the same time?

### What version of Cloudflared has the issue?

2.0.4

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
additional_hosts: []
external_hostname: url.com
tunnel_name: homeassistant
tunnel_token: ''
```

### Anything in the logs that might be useful for us?

```txt
Logs in description
```

### Steps to reproduce the issue

Call a TTS service
```
service: tts.google_say
data:
  entity_id: media_player.google_home
  message: test
  language: pl

```

**Comment by gerard33** [comment]
For me Google TTS is working fine with the Cloudflare addon.
Can you change the TTS settings by removing the `service_name` and `base_url`. Those variables are not part of the config shown [here](https://www.home-assistant.io/integrations/google_translate/) and the `base_url` seems to cause the error.

**Comment by pniewiadowski** [comment]
@gerard33 thanks a lot!
I've removed these settings and then HA shows me error that I don't have external_url set in General settings. I updated it, and now TTS works.
