### ISSUE TITLE
Cloudflared crashed

### ISSUE THREAD

**Issue by bordeo** [brenner-tobias/addon-cloudflared#195]
### The problem

Cloudflared crashed and I have no idea why

### What version of Cloudflared has the issue?

3.0.0

### What was the last working version of Cloudflared?

3.0.0

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
additional_hosts: []
external_hostname: my-hostname.com
tunnel_name: my-tunnel-name-****
tunnel_token: >-
  my-token-**********
```

### Anything in the logs that might be useful for us?

```txt
0x000000c00010ae10:  0x0000000000467b79 <os/signal.signal_enable+0x0000000000000079>  0x000000000000000f 
0x000000c00010ae20:  0x000000000041216e <runtime.mapassign_fast64ptr+0x000000000000028e>  0x000000c00005fe50 
0x000000c00010ae30:  0x000000000089bc53 <os/signal.Notify.func1+0x0000000000000073>  0x0000000000000000 
0x000000c00010ae40:  0x0000000000000090  0x000000000000000f 
0x000000c00010ae50:  0x000000c00005fec8  0x000000000089bb1f <os/signal.Notify+0x00000000000001ff> 
0x000000c00010ae60:  0x0000000000fa6da0  0x000000c00008e180 
0x000000c00010ae70:  0x000000c0000ac540  0x01000000000000a0 
0x000000c00010ae80:  0x000000c00005fec8  0x0000000000000000 
0x000000c00010ae90:  0x000000c000046340  0x000000c00005ff68 
0x000000c00010aea0:  0x000000000089bbe0 <os/signal.Notify.func1+0x0000000000000000>  0x000000c000046340 
0x000000c00010aeb0:  0x000000000089bce0 <os/signal.Notify.func2+0x0000000000000000>  0x0000000001afdec0 
0x000000c00010aec0:  0x000000c00005feb0 
runtime.sigenable(0xa6a53800)
	?:0 +0x276 fp=0xc00010adc7 sp=0xc00010adc0 pc=0x44cf96
created by github.com/cloudflare/cloudflared/cmd/cloudflared/tunnel.StartServer
	/cfsetup_build/cmd/cloudflared/tunnel/cmd.go:288 +0x66a
goroutine 1 [chan receive]:
github.com/prometheus/client_golang/prometheus.(*Registry).Register(0xc000106cd0, {0x133e818?, 0xc00011cf28?})
	/cfsetup_build/vendor/github.com/prometheus/client_golang/prometheus/registry.go:288 +0x250
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0006872a0?, {0xc0006872e0?, 0x1, 0x113c706?})
	/cfsetup_build/vendor/github.com/prometheus/client_golang/prometheus/registry.go:402 +0x53
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/cfsetup_build/vendor/github.com/prometheus/client_golang/prometheus/registry.go:178
github.com/cloudflare/cloudflared/connection.initTunnelMetrics()
	/cfsetup_build/connection/metrics.go:352 +0x11b
github.com/cloudflare/cloudflared/connection.newTunnelMetrics.func1()
	/cfsetup_build/connection/metrics.go:455 +0x17
sync.(*Once).doSlow(0x112a924?, 0x0?)
	/usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/cloudflare/cloudflared/connection.newTunnelMetrics()
	/cfsetup_build/connection/metrics.go:454 +0x31
github.com/cloudflare/cloudflared/connection.NewObserver(0xc0005c0d80, 0xc0005c0f00)
	/cfsetup_build/connection/observer.go:32 +0x27
github.com/cloudflare/cloudflared/cmd/cloudflared/tunnel.StartServer(0xc000678780, 0xc000661c20?, 0xc000661c20, 0xc0005c0d80)
	/cfsetup_build/cmd/cloudflared/tunnel/cmd.go:334 +0xba6
github.com/cloudflare/cloudflared/cmd/cloudflared/tunnel.(*subcommandContext).runWithCredentials(0xc00055f660, {{0xc0005cdd00, 0x20}, {0xc0005a9dd0, 0x24, 0x24}, {0x5b, 0xd1, 0xef, 0x86, ...}})
	/cfsetup_build/cmd/cloudflared/tunnel/subcommand_context.go:303 +0x15e
github.com/cloudflare/cloudflared/cmd/cloudflared/tunnel.runCommand(0xc000678780)
	/cfsetup_build/cmd/cloudflared/tunnel/subcommands.go:656 +0x278
github.com/cloudflare/cloudflared/cmd/cloudflared/cliutil.ConfiguredAction.func1(0x1ae6900?, {0xc00055f788?, 0x79b672?})
	/cfsetup_build/cmd/cloudflared/cliutil/handler.go:18 +0x1d
github.com/cloudflare/cloudflared/cmd/cloudflared/cliutil.ConfiguredActionWithWarnings.func1(0x7fba58a5f5b8?)
	/cfsetup_build/cmd/cloudflared/cliutil/handler.go:31 +0x51
github.com/cloudflare/cloudflared/cmd/cloudflared/cliutil.WithErrorHandler.func1(0xc000678780)
	/cfsetup_build/cmd/cloudflared/cliutil/errors.go:27 +0x37
github.com/urfave/cli/v2.(*Command).Run(0xc00059b9e0, 0xc00066dbc0)
	/cfsetup_build/vendor/github.com/urfave/cli/v2/command.go:163 +0x471
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc0003f5040, 0xc00066c480)
	/cfsetup_build/vendor/github.com/urfave/cli/v2/app.go:434 +0xb65
github.com/urfave/cli/v2.(*Command).startApp(0xc0005e87e0, 0xc00066c480)
	/cfsetup_build/vendor/github.com/urfave/cli/v2/command.go:279 +0x74f
github.com/urfave/cli/v2.(*Command).Run(0xc000664000?, 0x51?)
	/cfsetup_build/vendor/github.com/urfave/cli/v2/command.go:94 +0xaf
github.com/urfave/cli/v2.(*App).RunContext(0xc0003f4d00, {0x1343888?, 0xc00011a000}, {0xc000120000, 0x7, 0x7})
	/cfsetup_build/vendor/github.com/urfave/cli/v2/app.go:313 +0xa1d
github.com/urfave/cli/v2.(*App).Run(...)
	/cfsetup_build/vendor/github.com/urfave/cli/v2/app.go:224
main.runApp(0xc0003f4d00, 0xe?)
	/cfsetup_build/cmd/cloudflared/linux_service.go:36 +0x24d
main.main()
	/cfsetup_build/cmd/cloudflared/main.go:93 +0x909
goroutine 47 [chan receive]:
github.com/cloudflare/cloudflared/cmd/cloudflared/tunnel.notifySystemd(0x0?)
	/cfsetup_build/cmd/cloudflared/tunnel/cmd.go:443 +0x1e
created by github.com/cloudflare/cloudflared/cmd/cloudflared/tunnel.StartServer
	/cfsetup_build/cmd/cloudflared/tunnel/cmd.go:302 +0x84a
goroutine 48 [runnable]:
github.com/cloudflare/cloudflared/cmd/cloudflared/tunnel.StartServer.func3()
	/cfsetup_build/cmd/cloudflared/tunnel/cmd.go:309
created by github.com/cloudflare/cloudflared/cmd/cloudflared/tunnel.StartServer
	/cfsetup_build/cmd/cloudflared/tunnel/cmd.go:309 +0xa2f
goroutine 49 [runnable]:
github.com/prometheus/client_golang/prometheus.(*Registry).Register.func1()
	/cfsetup_build/vendor/github.com/prometheus/client_golang/prometheus/registry.go:276
created by github.com/prometheus/client_golang/prometheus.(*Registry).Register
	/cfsetup_build/vendor/github.com/prometheus/client_golang/prometheus/registry.go:276 +0x19b
[14:24:02] WARNING: cloudflared crashed, halting add-on
[14:24:02] INFO: cloudflared stoped, restarting...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service cloudflared: stopping
s6-rc: info: service cloudflared successfully stopped
s6-rc: info: service init-cloudflared-config: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service init-cloudflared-config successfully stopped
s6-rc: info: service init-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service init-log-level successfully stopped
s6-rc: info: service init-banner: stopping
s6-rc: info: service init-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Steps to reproduce the issue

I really don't know

**Comment by elcajon** [comment]
I guess this should be reported upstream as the error doesn't seem to be produced by the add-on itself.

**Comment by bordeo** [comment]
Fixed after hardware restart.
Thank you
