### ISSUE TITLE
Update to 4.2.9 failed

### ISSUE THREAD

**Issue by pschraml** [brenner-tobias/addon-cloudflared#509]
### The problem

Update failed to 4.2.9

### What version of Cloudflared has the issue?

4.2.9

### What was the last working version of Cloudflared?

4.2.7

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: name.ccc
additional_hosts:name.ccc
  - hostname: 
    service: https://xxx.xxx.xxx.xxx:8123
tunnel_name: HomeAssist
```

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:32:53 (1 occurrences)
Last logged: 22:32:53

[547305691712] Error updating Cloudflared: Can't install ghcr.io/brenner-tobias/cloudflared/aarch64:4.2.9: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=4.2.9&fromImage=ghcr.io%2Fbrenner-tobias%2Fcloudflared%2Faarch64&platform=linux%2Farm64: Internal Server Error ("Get "https://ghcr.io/v2/brenner-tobias/cloudflared/aarch64/manifests/sha256:eb940941019a36007cf8d70285b7330f0f5affe287fe6b0e802bafb2c6b04b9a": dial tcp 140.82.121.34:443: i/o timeout")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/brenner-tobias/cloudflared/aarch64:4.2.9: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=4.2.9&fromImage=ghcr.io%2Fbrenner-tobias%2Fcloudflared%2Faarch64&platform=linux%2Farm64: Internal Server Error ("Get "https://ghcr.io/v2/brenner-tobias/cloudflared/aarch64/manifests/sha256:eb940941019a36007cf8d70285b7330f0f5affe287fe6b0e802bafb2c6b04b9a": dial tcp 140.82.121.34:443: i/o timeout")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 432, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Cloudflared: Can't install ghcr.io/brenner-tobias/cloudflared/aarch64:4.2.9: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=4.2.9&fromImage=ghcr.io%2Fbrenner-tobias%2Fcloudflared%2Faarch64&platform=linux%2Farm64: Internal Server Error ("Get "https://ghcr.io/v2/brenner-tobias/cloudflared/aarch64/manifests/sha256:eb940941019a36007cf8d70285b7330f0f5affe287fe6b0e802bafb2c6b04b9a": dial tcp 140.82.121.34:443: i/o timeout")
```

### Steps to reproduce the issue

Not possible

**Comment by pschraml** [comment]
Updated again and now worked fine.

**Comment by Mod74** [comment]
I had the same problem, except it wouldn't load via the domain name. Had to go in via IP, update manually, and start it manually. Gave it a minute and working again.
